/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_sillero.vista;

import proyecto_sillero.controlador.CtrlIntroducirHoteles;
/**
 *
 * @author Rafa
 */
public class VistaJDIntroducirHoteles extends javax.swing.JDialog {
private CtrlIntroducirHoteles introducirControlador;

    /**
     * Creates new form JDialogIntroducir
     */
    public VistaJDIntroducirHoteles(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHotelesInsertar = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAnnadirHotel = new javax.swing.JMenu();
        jMenuItemAñadirHotel = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jTableHotelesInsertar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Hoteles"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableHotelesInsertar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableHotelesInsertarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableHotelesInsertar);
        if (jTableHotelesInsertar.getColumnModel().getColumnCount() > 0) {
            jTableHotelesInsertar.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        jMenuAnnadirHotel.setText("Opciones");
        jMenuAnnadirHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAnnadirHotelActionPerformed(evt);
            }
        });

        jMenuItemAñadirHotel.setText("Añadir hotel");
        jMenuItemAñadirHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAñadirHotelActionPerformed(evt);
            }
        });
        jMenuAnnadirHotel.add(jMenuItemAñadirHotel);

        jMenuBar1.add(jMenuAnnadirHotel);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAnnadirHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAnnadirHotelActionPerformed

    }//GEN-LAST:event_jMenuAnnadirHotelActionPerformed

    private void jMenuItemAñadirHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAñadirHotelActionPerformed
              introducirControlador.AbrirIntroducirHoteles();
    }//GEN-LAST:event_jMenuItemAñadirHotelActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
             
             
    }//GEN-LAST:event_formWindowGainedFocus

    private void jTableHotelesInsertarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableHotelesInsertarMouseClicked
        int columna = jTableHotelesInsertar.columnAtPoint(evt.getPoint());
        int fila = jTableHotelesInsertar.rowAtPoint(evt.getPoint());
           switch (columna) {
            case 0:
                introducirControlador.setNombreHotel(jTableHotelesInsertar.getValueAt(fila, columna).toString());
                
                introducirControlador.AbrirAnnadirClienteyTrabajador();
                break;
            default: 
                break;
           }
    }//GEN-LAST:event_jTableHotelesInsertarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaJDIntroducirHoteles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaJDIntroducirHoteles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaJDIntroducirHoteles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaJDIntroducirHoteles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VistaJDIntroducirHoteles dialog = new VistaJDIntroducirHoteles(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAnnadirHotel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAñadirHotel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableHotelesInsertar;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTable getjTableHotelesInsertar() {
        return jTableHotelesInsertar;
    }

    public void setIntroducirControlador(CtrlIntroducirHoteles introducirControlador) {
        this.introducirControlador = introducirControlador;
    }

  
    
  
 
    
    
    
    
    
    
    
    
    
    
}
